insert into user_account( FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, BANK, BALANCE) values ('Joffrey', 'Lefebvre', 'joffrey.lefebvre@gmail.com', '$2a$12$aExfPLQMwuoAn/QmeDRi2uPO9abXdoouLtuDpQH9inbOEtVU7DAhO', 'bankjoffrey', 200);
insert into user_account( FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, BANK, BALANCE) values ('spider', 'man', 'spiderman@marvel.com', '$2a$12$aExfPLQMwuoAn/QmeDRi2uPO9abXdoouLtuDpQH9inbOEtVU7DAhO', 'bankspiderman', 0);
insert into user_account( FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, BANK, BALANCE) values ('Captain', 'America', 'captain@marvel.com', '$2a$12$aExfPLQMwuoAn/QmeDRi2uPO9abXdoouLtuDpQH9inbOEtVU7DAhO', 'bankcaptain', 0);
insert into user_account( FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, BANK, BALANCE) values ('Iron', 'man', 'ironman@marvel.com', '$2a$12$aExfPLQMwuoAn/QmeDRi2uPO9abXdoouLtuDpQH9inbOEtVU7DAhO', 'bankironman', 0);
insert into user_account( FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, BANK, BALANCE) values ('Thor', 'Thor', 'thor@marvel.com', '$2a$12$aExfPLQMwuoAn/QmeDRi2uPO9abXdoouLtuDpQH9inbOEtVU7DAhO', 'bankthor', 0);

insert into transaction(DATE, AMOUNT, DESCRIPTION, CREDITOR_ID, DEBTOR_ID) VALUES ('2023-04-07', 99.99, 'test', (SELECT id from user_account where email = 'spiderman@marvel.com'), (SELECT id from user_account where email = 'joffrey.lefebvre@gmail.com'));
insert into transaction(DATE, AMOUNT, DESCRIPTION, CREDITOR_ID, DEBTOR_ID) VALUES ('2023-04-07', 99.99, 'test', (SELECT id from user_account where email = 'joffrey.lefebvre@gmail.com'), (SELECT id from user_account where email = 'spiderman@marvel.com'));
insert into transaction(DATE, AMOUNT, DESCRIPTION, CREDITOR_ID, DEBTOR_ID) VALUES ('2023-04-05', 99.99, 'test', (SELECT id from user_account where email = 'joffrey.lefebvre@gmail.com'), (SELECT id from user_account where email = 'ironman@marvel.com'));
insert into transaction(DATE, AMOUNT, DESCRIPTION, CREDITOR_ID, DEBTOR_ID) VALUES ('2023-04-10', 200, 'test', (SELECT id from user_account where email = 'joffrey.lefebvre@gmail.com'), (SELECT id from user_account where email = 'thor@marvel.com'));
insert into transaction(DATE, AMOUNT, DESCRIPTION, CREDITOR_ID, DEBTOR_ID) VALUES ('2023-04-01', 99.99, 'test', (SELECT id from user_account where email = 'captain@marvel.com'), (SELECT id from user_account where email = 'joffrey.lefebvre@gmail.com'));
insert into transaction(DATE, AMOUNT, DESCRIPTION, CREDITOR_ID, DEBTOR_ID) VALUES ('2023-04-01', 100.99, 'test', (SELECT id from user_account where email = 'captain@marvel.com'), (SELECT id from user_account where email = 'joffrey.lefebvre@gmail.com'));

insert into user_account_contact_list(USER_ACCOUNT_ID, CONTACT_LIST_ID) VALUES (1, (SELECT id from user_account where email = 'spiderman@marvel.com'));